### PR TITLE
Update impute_aphea2_sydney_pm25.Rmd

### PR DESCRIPTION
**Pull request by farhadsalimi**
changed dataset names to more appropriate ones,
will use average of the neighbour two days if only NA's are less than 5%
It assumes the new csv files Ivan (the latest ones I sent you)

### CODE REVIEW

**Comment by ivanhanigan** [comment]
thanks running this now

**Comment by ivanhanigan** [comment]
Hey thanks for this.
I'm able to read your code but not run your codes as I still get this error.
I can only see imputation of PM2.5 is that right?
Are you going to impute the other pollutants with APHEA2 too? 

Below error I think it does not know what is WS? 

``` r
> nswaq9413.daily.avg <- timeAverage (nswaq9413, avg.time = "day", data.thresh = 75, interval = "hour")
Error: Unknown name
> traceback()
5: stop("Unknown name", call. = FALSE)
4: `$.tbl_df`(mydata, "ws")
3: mydata$ws
2: checkPrep(mydata, vars, type = "default", remove.calm = FALSE,
       strip.white = FALSE)
1: timeAverage(nswaq9413, avg.time = "day", data.thresh = 75, interval = "hour")
```

**Comment by ivanhanigan** [comment]
Hey thanks for this.
I'm able to read your code but not run your codes as I still get this error.
I can only see imputation of PM2.5 is that right?
Are you going to impute the other pollutants with APHEA2 too?

Below error I think it does not know what is WS?

`r
> nswaq9413.daily.avg <- timeAverage (nswaq9413, avg.time = "day",
data.thresh = 75, interval = "hour")
Error: Unknown name
> traceback()
5: stop("Unknown name", call. = FALSE)
4: `$.tbl_df`(mydata, "ws")
3: mydata$ws
2: checkPrep(mydata, vars, type = "default", remove.calm = FALSE,
       strip.white = FALSE)
1: timeAverage(nswaq9413, avg.time = "day", data.thresh = 75, interval =
"hour")
`

**Comment by farhadsalimi** [comment]
@ivanhanigan 
i don't know why it is giving that error, we are not selecting wind speed at all and it shouldn't complain when there is no column, which version of openair you are using?

**Comment by ivanhanigan** [comment]
openair_1.6.7

I also used 8GB of RAM and 4GB of Swap space getting that far.  I
think the PostGIS approach still has merits as it uses disk instead.

**Comment by farhadsalimi** [comment]
i have the same version, so weird. 
One way around it is to keep the ws column just to make it happy.
I haven't imputed the other variables yet but it is in my plan. I need to find a way to efficiently impute all variables at once without using a for loop.

**Comment by ivanhanigan** [comment]
looks like your codes work on windows but not linux.
I am running this now on Geoff's VM in lismore.
Do you have access to the Q drive?

**Comment by ivanhanigan** [comment]
@farhadsalimi 
Hi
Seeing as this is not really about events but about the daily time-series I have moved it to a new home

https://github.com/swish-climate-impact-assessment/AP_monitor_NSW_1994_2013_hrly/blob/master/main.R

We can continue to work on the impute_aphea2 function in the BiosmokeValidatedEvents R package as it is useful for creating the percentiles needed for event validation, but the actual processing of time-series is not part of this package

**Pull request merged**
